### ISSUE TITLE
Creating a new employee can't be done without providing a value for the emp_code field.

### ISSUE THREAD

**Issue by redtrinity** [TheAlphaSchoolSystemPTYLTD/APIBetaTesting#8]
Creating a new employee record without a value for `emp_code` returns this error:
```
emp_code: ['Field is required for this endpoint.']
```

Ideally this endpoint should not require the `emp_code` value when creating an employee record which would replicate the behaviour in TASS.web; this value isn't provided when creating an employee record in TASS.web (at least if TASS is set up to auto increment new records, if I recall correctly this is the default behaviour for employee records).

It would also potentially be problematic to provide this in scenarios where an API call to create a new employee is processed at the same time a new employee record is created through the TASS.web UI.

Related to #3 .

**Comment by scottetass** [comment]
Hi,

The emp_code has to be in the request but it should be blank if using auto-numbering. We had to do it this way so that we could cater for both scenarios - those using auto-numbering and those that don't. Otherwise, we'd have to define two separate endpoints, one that includes emp_code in the request and the other that doesn't.

I'll see about updating documentation to make this a bit clearer for that particular field.

Thanks, Scott
