### ISSUE TITLE
FR: Last updated by info on records should also reflect the API User

### ISSUE THREAD

**Issue by redtrinity** [TheAlphaSchoolSystemPTYLTD/APIBetaTesting#9]
When looking at records that have a `Last Updated By` info page, if possible it would be very helpful if this also indicated which API user made the change; for example, if an API user is created to integrate with a third party HR platform and that third party HR platform creates/modifies employee records, being able to view that API user detail in the update info will help save time investigating any audit logs if it's required to understand the chain of change.

![Screen_Shot_2024-12-05-084715-805346](https://github.com/user-attachments/assets/9ce866aa-54e4-4f39-8232-ba99e76b1f4a)

**Comment by scottetass** [comment]
Hi,

Unfortunately, in most places in the database, the update_by field has a maximum of 10 characters but our API username can be 100 characters. Thats why we used the generic RESTAPI value. Leave this one with me while I investigate if it's possible or not.

Thanks, Scott

**Comment by scottetass** [comment]
Hi,

Unfortunately, we only have 7 characters to work with for the ‘updated by’ value, not 10 as hinted at above. Another negative aspect of the ‘update by’ field is that currently, we don’t know what type of user it was that performed the update – was it a teacher, student, parent, TASS user or API user? I think we need to somehow indicate that it was the API updating the record but when we only have 7 characters to do that, the tricky part is how to indicate an update was from the API **and** the user who performed it.

My initial thinking was to allow a ‘user code’ to be entered when you create a new API user, then, when updating a record via the API, setting the ‘updated by’ value to something like ‘API-<user code>’. That way, you know the update as performed by the API and you can relate the user code to the user in the API maintenance screens. But due to only having 7 characters to work with, that only leaves 3 characters for a user code, not really a lot to allow you to identify a user properly.

Unfortunately, we can’t increase the size for ‘update by’ in TASS because there are 100+ tables that would need updating and trying to make all those changes and test is an enormous amount of work.

So it doesn’t leave a lot of options really:

- Just put the first 7 characters of the API username in to the ‘update by’ field but you’ll have trouble determining what type of user it is (teacher, student, parent, TASS user, API user).

- Create a client/user code of 3 characters and set ‘update by’ to API-XXX but is three characters enough to identify the user?

- Create a client/user code of 7 characters and set ‘update by’ to that, but again, but you’ll have trouble determining what type of user it is

I'd be happy to get your feedback on the above options or an alternative, keeping within the maximum 7 character limit. What would make it easier for you to identify the correct user?

Thanks, Scott

**Comment by redtrinity** [comment]
It would be preferable to have a _six_ digit value that was automatically generated and prefixed with the value `A` to denote API user ID, so in theory there'd be a range of `A000000` to `A999999` values available, which should provide an ample number of API users to play with (well, it certainly would for my circumstances).

This should allow for that user code to inserted into the relevant audit logging tables and data tables and not bump the 7 character length limit for the `update_by` or other applicable columns across TASS.

**Comment by scottetass** [comment]
Would API9999 work as well? It describes a little bit more that it relates to an API update and still gives you up to 10,000 users, which i doubt anyone would hit that limit any time soon.

**Comment by redtrinity** [comment]
Yes that would work just as well, having a more descriptive prefix would work better.

**Comment by scottetass** [comment]
Hi,

This has been done and will be available in the next build (#5300).

When performing an add/update via the API and the entity being updated supports 'update_by', then it will be set to a unique user code in the format API9999.

Thanks, Scott
